// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClE-QgOKdnMTLiugP-hDM1k1HVXMPr3n8',
    appId: '1:331231769661:web:9e2357c819aa2fc5572654',
    messagingSenderId: '331231769661',
    projectId: 'word-game-99398',
    authDomain: 'word-game-99398.firebaseapp.com',
    storageBucket: 'word-game-99398.appspot.com',
    measurementId: 'G-B776KY0S9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaf06pbupo1mRRtDa1VT4fPvtsOwk9JAc',
    appId: '1:331231769661:android:87ba07e987b72bfa572654',
    messagingSenderId: '331231769661',
    projectId: 'word-game-99398',
    storageBucket: 'word-game-99398.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1qmEURqUy-qwboKOiRHmlWWZyY4998Hg',
    appId: '1:331231769661:ios:4620605023ede710572654',
    messagingSenderId: '331231769661',
    projectId: 'word-game-99398',
    storageBucket: 'word-game-99398.appspot.com',
    iosBundleId: 'com.mulmemetco.keith.wordgame.wordGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1qmEURqUy-qwboKOiRHmlWWZyY4998Hg',
    appId: '1:331231769661:ios:4620605023ede710572654',
    messagingSenderId: '331231769661',
    projectId: 'word-game-99398',
    storageBucket: 'word-game-99398.appspot.com',
    iosBundleId: 'com.mulmemetco.keith.wordgame.wordGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClE-QgOKdnMTLiugP-hDM1k1HVXMPr3n8',
    appId: '1:331231769661:web:8bdd13b63dd81c32572654',
    messagingSenderId: '331231769661',
    projectId: 'word-game-99398',
    authDomain: 'word-game-99398.firebaseapp.com',
    storageBucket: 'word-game-99398.appspot.com',
    measurementId: 'G-N4NXHXPJGH',
  );
}
